//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManifest.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssetManifest.Database.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;component_types&quot; (
        ///                                   &quot;id&quot;	TEXT NOT NULL UNIQUE,
        ///                                   &quot;type&quot;	TEXT UNIQUE ,
        ///                                   PRIMARY KEY(&quot;id&quot;)
        ///);
        ///
        ///CREATE TABLE &quot;property_data&quot; (
        ///	&quot;id&quot;	INTEGER NOT NULL,
        ///	&quot;component_id&quot;	TEXT,
        ///	&quot;property_name&quot;	INTEGER,
        ///	&quot;is_collection&quot;	INTEGER,
        ///	&quot;collection_index&quot;	INTEGER,
        ///	PRIMARY KEY(&quot;id&quot; AUTOINCREMENT)
        ///);
        ///
        ///CREATE TABLE &quot;asset_locations&quot; (
        ///    &quot;id&quot; INTEGER NOT NULL,
        ///    &quot;base_gameobject&quot;	TEXT,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
    }
}
